services:
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      POSTGRES_PASSWORD: ramze_akbar_agha
      POSTGRES_USER: akbar_agha
      POSTGRES_DB: database_akbar_agha
    networks:
      - my_network_2
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai_web_app:
    image: ai_web_app
    container_name: ai_web_app
    networks:
      - my_network_2
    ports:
      - "8080:5000"
    volumes:
      - .:/myapp
    depends_on:
      - postgres

networks:
  my_network_2:

volumes:
  postgres_data:

